### ISSUE TITLE
PyTest not working in dev

### ISSUE THREAD

**Issue by galjos** [MolarVerse/PQAnalysis#21]
**Describe the bug**
pytest does not start in dev, since it could not recognize arguments.

**To Reproduce**
- Clean environment with Python 3.12.3: `python -m venv venv`
- Activate env: `source venv/bin/activate`
- Install project: `pip install .`
- Try testing: `pytest` (Maybe add as depedency, for easy use)

```
$ pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=PQAnalysis --cov-report=html
  inifile: /home/jog/projects/PQAnalysis/pytest.ini
  rootdir: /home/jog/projects/PQAnalysis
```

**Expected behavior**
Should result in test execution.

**Comment by 97gamjak** [comment]
Did you try ``pip install .[test]``?

The test dependencies are only optional dependencies. In the next release
to main this will be included in the developer guide in the documentation.

**Comment by galjos** [comment]
`pip install '.[test]'` did work, but still same issue

**Comment by 97gamjak** [comment]
Ok, I'll check it out.

**Comment by 97gamjak** [comment]
@galjos I reproduced now exactly each step as given in the description and it works on my side.

Could you try to write ``python -m pytest `` instead

**Comment by galjos** [comment]
Works
