### ISSUE TITLE
Nep needs uppercase atom names

### ISSUE THREAD

**Issue by benjibre** [MolarVerse/PQAnalysis#22]
Since nep needs uppercased atom names build_nep_traj should generate output including the atomnames as their uppercase version. 

**To Reproduce**
Run nep with test.xyz and train.xyz files with unchanged output files from build_nep_traj. Generates an input error when trying to read train.xyz

**Comment by 97gamjak** [comment]
Should work now could you please test it

**Comment by benjibre** [comment]
It is fixed thank you!
