### ISSUE TITLE
Test empty rule Handling of all readers

### ISSUE THREAD

**Issue by galjos** [MolarVerse/PQAnalysis#46]
BaseReader does not check for empty files. In my opinion, since function such as `calculate_number_of_frames` fail when files are empty, I would raise an Exception to ensure that the function to work properly.

**Comment by 97gamjak** [comment]
Good point.

Is there really no special use case of reading an empty file and continuing with processing stuff?

Probably it would be best to keep the behavior of the `BaseReader` as _defaultish_ as possible, meaning that the reading should be performed as most other readers do (in any language I can think of). So best would be to really cover the special cases.

**Comment by 97gamjak** [comment]
We should explicitly test all readers if theor empty file handling makes sense
