### ISSUE TITLE
Energy should contain base-filename

### ISSUE THREAD

**Issue by galjos** [MolarVerse/PQAnalysis#8]
`Energy` should, in my opinion, contain the base name of the original `energy_filename`, so that it can be distinguished from other `Energy` classes

**Comment by 97gamjak** [comment]
In gemeral i think a user could handle this by specific naming of the object. But of course when dealing with lists it might be useful to introduce a id: str as an identifier. 

By introducing an optional keyword argument in the init statement the user can set the id himself and in the energyfilereader the filename would make sense. 

But I would rather use the full file name to avoid naming collisions as e.g. "data.en" and "data.dat"

**Comment by 97gamjak** [comment]
Is this still an issue? so is there any need for this feature?

**Comment by galjos** [comment]
No, I found another solution🤝
